// <auto-generated />
using MajorInteractiveBot.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MajorInteractiveBot.Data.Migrations
{
    [DbContext(typeof(MajorContext))]
    [Migration("20190724233910_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("MajorInteractiveBot.Data.Models.CommandChannel", b =>
                {
                    b.Property<ulong>("ChannelId")
                        .ValueGeneratedOnAdd();

                    b.Property<ulong>("GuildId");

                    b.HasKey("ChannelId");

                    b.HasIndex("GuildId");

                    b.ToTable("CommandChannels");
                });

            modelBuilder.Entity("MajorInteractiveBot.Data.Models.Guild", b =>
                {
                    b.Property<ulong>("GuildId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CommandPrefix");

                    b.Property<bool>("GreetUser");

                    b.Property<ulong>("GreetingChannel");

                    b.Property<string>("GreetingMessage");

                    b.HasKey("GuildId");

                    b.ToTable("Guilds");
                });

            modelBuilder.Entity("MajorInteractiveBot.Data.Models.Module", b =>
                {
                    b.Property<string>("ModuleName")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Enabled");

                    b.Property<ulong>("GuildId");

                    b.HasKey("ModuleName");

                    b.HasIndex("GuildId");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("MajorInteractiveBot.Data.Models.Tag", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<ulong>("GuildId");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("MajorInteractiveBot.Data.Models.CommandChannel", b =>
                {
                    b.HasOne("MajorInteractiveBot.Data.Models.Guild")
                        .WithMany("CommandChannels")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MajorInteractiveBot.Data.Models.Module", b =>
                {
                    b.HasOne("MajorInteractiveBot.Data.Models.Guild")
                        .WithMany("Modules")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MajorInteractiveBot.Data.Models.Tag", b =>
                {
                    b.HasOne("MajorInteractiveBot.Data.Models.Guild")
                        .WithMany("Tags")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
