// <auto-generated />
using MajorInteractiveBot.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MajorInteractiveBot.Data.Migrations
{
    [DbContext(typeof(MajorContext))]
    [Migration("20190725043054_RestructureGuild")]
    partial class RestructureGuild
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("MajorInteractiveBot.Data.Models.CommandChannel", b =>
                {
                    b.Property<ulong>("ChannelId")
                        .ValueGeneratedOnAdd();

                    b.Property<ulong>("GuildId");

                    b.HasKey("ChannelId");

                    b.ToTable("CommandChannels");
                });

            modelBuilder.Entity("MajorInteractiveBot.Data.Models.Guild", b =>
                {
                    b.Property<ulong>("GuildId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CommandPrefix");

                    b.Property<bool>("GreetUser");

                    b.Property<ulong>("GreetingChannel");

                    b.Property<string>("GreetingMessage");

                    b.HasKey("GuildId");

                    b.ToTable("Guilds");
                });

            modelBuilder.Entity("MajorInteractiveBot.Data.Models.Module", b =>
                {
                    b.Property<ulong>("GuildId");

                    b.Property<string>("ModuleName");

                    b.Property<bool>("Enabled");

                    b.HasKey("GuildId", "ModuleName");

                    b.ToTable("Modules");
                });
#pragma warning restore 612, 618
        }
    }
}
